apiVersion: apps/v1
kind: Deployment
metadata:
  name: zico-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zicodev
  template:
    metadata:
      labels:
        app: zicodev
    spec:
      containers:
      - name: zicodev
        image: 998284843362.dkr.ecr.us-east-1.amazonaws.com/zicodev
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: zicodev
    k8s-app: zicodev
  name: zicodev
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: zicodev
